<Project Sdk="Microsoft.NET.Sdk">



  <ItemGroup>

    <ProjectReference Include="..\TarifDefterim.Application\TarifDefterim.Application.csproj" />

    <ProjectReference Include="..\TarifDefterim.Domain\TarifDefterim.Domain.csproj" />

  </ItemGroup>



  <ItemGroup>

    <PackageReference Include="CloudinaryDotNet" Version="1.29.2" />

    <PackageReference Include="MailKit" Version="4.17.0" />

    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">

      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>

      <PrivateAssets>all</PrivateAssets>

    </PackageReference>

    <PackageReference Include="HtmlSanitizer" Version="9.0.889" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />

  </ItemGroup>



  <PropertyGroup>

    <TargetFramework>net10.0</TargetFramework>

    <ImplicitUsings>enable</ImplicitUsings>

    <Nullable>enable</Nullable>

  </PropertyGroup>



  <ItemGroup>

    <None Update="EmailTemplates\**\*.html">

      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>

    </None>

  </ItemGroup>



</Project>


